apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
  namespace: argocd
  finalizers:
    # Limpia los recursos del clúster cuando se borra la Application
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    # Repositorio GitHub utilizado por Argo CD
    repoURL: https://github.com/Anatarqu/HT4---GitOps.git
    targetRevision: main
    path: 01-crossplane

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true