@'
# =====================================================================
# Crossplane Claim — PostgreSQLInstance
# =====================================================================
# Realizado: Instancia simplificada para el equipo de desarrollo
# =====================================================================

apiVersion: database.poc.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: mi-base-de-datos
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Valores para los parámetros definidos en el esquema OpenAPI de tu XRD
  dbName: ecommercedb
  owner: app_developer
'@ | Set-Content .\01-crossplane\claim.yaml