apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresql-composition
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  compositeTypeRef:
    apiVersion: database.poc.io/v1alpha1
    kind: XPostgreSQLInstance

  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: postgresql-database
            base:
              apiVersion: postgresql.sql.crossplane.io/v1alpha1
              kind: Database
              spec:
                forProvider:
                  name: "placeholder"
                  owner: "postgres"
                providerConfigRef:
                  name: postgresql-config
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.dbName"
                toFieldPath: "spec.forProvider.name"
                policy:
                  fromFieldPath: Required

              - type: FromCompositeFieldPath
                fromFieldPath: "spec.owner"
                toFieldPath: "spec.forProvider.owner"
                policy:
                  fromFieldPath: Required
