apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: postgresql-config
spec:
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      name: postgresql-creds
      namespace: default
